SELECT 
CASE 
    WHEN CAST(DATE_FORMAT(DIFFERENTIATION_DATE, '%m') AS UNSIGNED) < 4
    THEN '1Q'
    WHEN CAST(DATE_FORMAT(DIFFERENTIATION_DATE, '%m') AS UNSIGNED) < 7
    THEN '2Q'
    WHEN CAST(DATE_FORMAT(DIFFERENTIATION_DATE, '%m') AS UNSIGNED) < 10
    THEN '3Q'
    ELSE '4Q'
END QUARTER,
COUNT(*) ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER
